language: python

python:
    - 3.8.3

install:
    - pip3 install -r requirements.txt

script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate

notifications:
  email:
    on_success: never # default: change
    on_failure: always
    
  slack:
        if: branch = master
            email:
                on_success: never # default: change
                on_failure: always
