language: python
python:
    - 3.8.3
install:
    - pip3 install -r requirements.txt
script:
    - python3 manage.py test
deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: andromed-airlines
    run: python3 manage.py migrate
    on: master
